# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{alchemy_api}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Balatero"]
  s.date = %q{2010-11-02}
  s.description = %q{Provides a client API library for AlchemyAPI's awesome NLP services. Allows you to make parallel or serial requests.}
  s.email = %q{dbalatero@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown",
     "README.markdown.html"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "CHANGELOG.markdown",
     "Gemfile",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "alchemy_api.gemspec",
     "lib/alchemy_api.rb",
     "lib/alchemy_api/base.rb",
     "lib/alchemy_api/categorization.rb",
     "lib/alchemy_api/concept_tagging.rb",
     "lib/alchemy_api/language_detection.rb",
     "lib/alchemy_api/term_extraction.rb",
     "lib/alchemy_api/text_extraction.rb",
     "spec/alchemy_api/base_spec.rb",
     "spec/alchemy_api/categorization_spec.rb",
     "spec/alchemy_api/concept_tagging_spec.rb",
     "spec/alchemy_api/language_detection_spec.rb",
     "spec/alchemy_api/term_extraction_spec.rb",
     "spec/alchemy_api/text_extraction_spec.rb",
     "spec/alchemy_api_spec.rb",
     "spec/cache/categorization/get_categorization_from_html/ddc3cf50efe5bd5c2159abfb49121cfa2314ca88.cache",
     "spec/cache/categorization/get_categorization_from_text/8b476a3b532afd2da646b145e9dde07570c27352.cache",
     "spec/cache/categorization/get_categorization_from_url/7536a34e1d54a95d8ee07d2a98036362761e1621.cache",
     "spec/cache/concept_tagging/get_concepts_from_html/7da223513abcfe2fd3d253fff60894829f858667.cache",
     "spec/cache/concept_tagging/get_concepts_from_text/3e56901d7f01729b79ef73fc6d34fa97148eb35c.cache",
     "spec/cache/concept_tagging/get_concepts_from_url/488c7dbb9b844b072cb284425b4ca8356b08dd15.cache",
     "spec/cache/language_detection/get_language_from_html/0faf7be978647b611d9c59e1efa497dd76e542f5.cache",
     "spec/cache/language_detection/get_language_from_text/1ad3f50c1fda37000e24c196f12212ea9d536cb4.cache",
     "spec/cache/language_detection/get_language_from_url/d077a95e60be0876bb7650ad213f5f43e83454d4.cache",
     "spec/cache/term_extraction/get_ranked_keywords_from_html/7718a0fbd03739e4213a4e66c32a79a10c3499c3.cache",
     "spec/cache/term_extraction/get_ranked_keywords_from_text/6f49e68ee4a9150368e671e70b632dbdc40860bb.cache",
     "spec/cache/term_extraction/get_ranked_keywords_from_url/b9c291523159563d2224d676ec43b7b79a902d21.cache",
     "spec/cache/text_extraction/get_raw_text_from_html/9db19f848a798db1f9a8c6cce9074d03cf2637a8.cache",
     "spec/cache/text_extraction/get_raw_text_from_html/e9c236b6e861b57d238c810bb3c307cada170cad.cache",
     "spec/cache/text_extraction/get_raw_text_from_url/8f5dff27211163e41ea5e7c3c534acf7b87d2098.cache",
     "spec/cache/text_extraction/get_text_from_html/e7e6dba4c8570a41dbcb05233793018fc5ae4e1e.cache",
     "spec/cache/text_extraction/get_text_from_url/13facbfeae029d936c7dc18ecaff5d2764b94618.cache",
     "spec/cache/text_extraction/get_title_from_html/2a526348db23f992fee293d34f94c087e77290c5.cache",
     "spec/cache/text_extraction/get_title_from_url/e84c0c7c67668706ae0cf3eefcd88c0911cd2b65.cache",
     "spec/fixtures/article.txt",
     "spec/fixtures/bp_spill.html",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/dbalatero/alchemy_api}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Provides a client API library for AlchemyAPI's awesome NLP services. Allows you to make parallel or serial requests.}
  s.test_files = [
    "spec/alchemy_api/base_spec.rb",
     "spec/alchemy_api/categorization_spec.rb",
     "spec/alchemy_api/concept_tagging_spec.rb",
     "spec/alchemy_api/language_detection_spec.rb",
     "spec/alchemy_api/term_extraction_spec.rb",
     "spec/alchemy_api/text_extraction_spec.rb",
     "spec/alchemy_api_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<typhoeus_spec_cache>, [">= 0.2.2"])
      s.add_runtime_dependency(%q<monster_mash>, [">= 0.1.1"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<typhoeus_spec_cache>, [">= 0.2.2"])
      s.add_dependency(%q<monster_mash>, [">= 0.1.1"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<typhoeus_spec_cache>, [">= 0.2.2"])
    s.add_dependency(%q<monster_mash>, [">= 0.1.1"])
  end
end

